variable "agent_name" {
  description = "Agent name (lowercase, no spaces)."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$", var.agent_name))
    error_message = "agent_name must be lowercase alphanumeric with hyphens, 2-63 chars."
  }
}

variable "resource_group_name" {
  description = "Resource group that holds the agent, identity, LAW, and App Insights."
  type        = string
}

variable "location" {
  description = "Azure region. Only regions supported by the SRE Agent RP."
  type        = string
  default     = "eastus2"

  validation {
    condition     = contains(["swedencentral", "uksouth", "eastus2", "australiaeast"], var.location)
    error_message = "location must be one of: swedencentral, uksouth, eastus2, australiaeast."
  }
}

variable "target_resource_groups" {
  description = "Resource group names the agent is granted access to."
  type        = list(string)
  default     = []
}

variable "access_level" {
  description = "Low = read-only investigation. High = can take actions."
  type        = string
  default     = "Low"

  validation {
    condition     = contains(["High", "Low"], var.access_level)
    error_message = "access_level must be High or Low."
  }
}

variable "action_mode" {
  description = "Review = human approval. Automatic = agent acts independently."
  type        = string
  default     = "Review"

  validation {
    condition     = contains(["Review", "Automatic"], var.action_mode)
    error_message = "action_mode must be Review or Automatic."
  }
}

variable "upgrade_channel" {
  description = "Upgrade channel for the agent runtime."
  type        = string
  default     = "Preview"

  validation {
    condition     = contains(["Stable", "Preview"], var.upgrade_channel)
    error_message = "upgrade_channel must be Stable or Preview."
  }
}

variable "monthly_agent_unit_limit" {
  description = "Monthly agent unit consumption limit."
  type        = number
  default     = 10000
}

variable "default_model_provider" {
  description = "Default LLM provider (MicrosoftFoundry, Anthropic)."
  type        = string
  default     = "Anthropic"
}

variable "default_model_name" {
  description = "Default LLM model name."
  type        = string
  default     = "Automatic"
}

variable "tags" {
  description = "Azure resource tags applied to the agent and supporting resources."
  type        = map(string)
  default     = {}
}

# ── Apps ──

variable "deploy_apps" {
  description = "Deploy the orders-api and change-lookup Container Apps."
  type        = bool
  default     = true
}

variable "acr_sku" {
  description = "SKU for the Azure Container Registry."
  type        = string
  default     = "Basic"
}

variable "aks_node_vm_size" {
  description = "VM size for the AKS system node pool."
  type        = string
  default     = "Standard_B2s"
}

variable "aks_min_count" {
  description = "Minimum node count for the AKS system node pool autoscaler."
  type        = number
}

variable "aks_max_count" {
  description = "Maximum node count for the AKS system node pool autoscaler."
  type        = number
}

variable "aks_user_node_vm_size" {
  description = "VM size for the AKS user node pool."
  type        = string
  default     = "Standard_B2s"
}

variable "aks_user_min_count" {
  description = "Minimum node count for the AKS user node pool autoscaler."
  type        = number
  default     = 1
}

variable "aks_user_max_count" {
  description = "Maximum node count for the AKS user node pool autoscaler."
  type        = number
  default     = 2
}

# The AKS SSH key pair is generated by Terraform to keep plans/apply CI-safe.

variable "aks_pod_cidr" {
  description = "Pod CIDR for Azure CNI overlay networking."
  type        = string
  default     = "10.244.0.0/16"
}

variable "aks_service_cidr" {
  description = "Kubernetes service CIDR for AKS."
  type        = string
  default     = "10.0.0.0/16"
}

variable "aks_dns_service_ip" {
  description = "DNS service IP for AKS."
  type        = string
  default     = "10.0.0.10"
}

variable "aks_vnet_cidr" {
  description = "Address space for the AKS virtual network."
  type        = string
  default     = "10.50.0.0/16"
}

variable "aks_subnet_cidr" {
  description = "Subnet range used by AKS nodes."
  type        = string
  default     = "10.50.1.0/24"
}

variable "existing_managed_identity_id" {
  description = "Resource ID of an existing UAMI. If provided, skips creating a new one."
  type        = string
  default     = ""
}

variable "existing_agent_app_insights_id" {
  description = "Resource ID of an existing Application Insights for agent telemetry. If provided, skips creating a new one."
  type        = string
  default     = ""
}

# ── Networking ──

variable "enable_vnet" {
  description = "Create a dedicated virtual network for the agent."
  type        = bool
  default     = false
}

variable "existing_subnet_id" {
  description = "Resource ID of an existing subnet to use instead of creating a new VNet."
  type        = string
  default     = ""
}

variable "vnet_address_space" {
  description = "Address space for the agent virtual network."
  type        = string
  default     = "10.70.0.0/16"
}

variable "agent_subnet_prefix" {
  description = "Subnet range used by the agent."
  type        = string
  default     = "10.70.0.0/24"
}

# ── Connector toggles ──

variable "enable_app_insights_connector" {
  description = "Enable an Application Insights connector."
  type        = bool
  default     = false
}

variable "app_insights_resource_id" {
  description = "Full Azure resource ID of the App Insights component."
  type        = string
  default     = ""
}

variable "app_insights_app_id" {
  description = "App Insights Application ID (GUID from the Overview blade)."
  type        = string
  default     = ""
}

variable "enable_log_analytics_connector" {
  description = "Enable a Log Analytics connector."
  type        = bool
  default     = false
}

variable "law_resource_id" {
  description = "Full Azure resource ID of the LAW workspace."
  type        = string
  default     = ""
}

variable "enable_azure_monitor_connector" {
  description = "Enable an Azure Monitor connector (subscription-scoped alerts)."
  type        = bool
  default     = false
}

variable "enable_service_now_connector" {
  description = "Configure ServiceNow as the incident platform during recipe extras."
  type        = bool
  default     = false
}

variable "service_now_instance" {
  description = "ServiceNow instance URL, for example https://example.service-now.com."
  type        = string
  default     = ""
}

variable "service_now_username" {
  description = "ServiceNow username used by the incident platform integration."
  type        = string
  default     = ""
  sensitive   = true
}

variable "service_now_password" {
  description = "ServiceNow password used by the incident platform integration."
  type        = string
  default     = ""
  sensitive   = true
}

variable "azure_monitor_lookback_days" {
  description = "Lookback window in days for the Azure Monitor connector."
  type        = number
  default     = 7
}

variable "enable_sev01_incident_filter" {
  description = "Register the optional Sev0/Sev1 Azure Monitor incident response plan during post-provision."
  type        = bool
  default     = false
}

variable "enable_daily_health_check" {
  description = "Register the optional daily health check automation during post-provision."
  type        = bool
  default     = false
}

# ── Extension arrays (advanced) ──

variable "skills" {
  description = "Skill definitions. Each entry: { name, spec = { ... } }."
  type = list(object({
    name = string
    spec = any
  }))
  default = []
}

variable "subagents" {
  description = "Subagent definitions. Each entry: { name, spec = { ... } }."
  type = list(object({
    name = string
    spec = any
  }))
  default = []
}

variable "connectors" {
  description = "Additional connector definitions (beyond toggle-generated ones). Each entry: { name, properties = { dataConnectorType, dataSource, extendedProperties, identity } }."
  type        = any
  default     = []
}

variable "common_prompts" {
  description = "Common prompt definitions. Each entry: { name, properties = { prompt } }."
  type = list(object({
    name       = string
    properties = any
  }))
  default = []
}

variable "tools" {
  description = "Tool definitions. Each entry: { name, spec = { ... } }."
  type = list(object({
    name = string
    spec = any
  }))
  default = []
}

variable "enable_webhook_bridge" {
  description = "Deploy a Logic App webhook bridge for HTTP trigger ingestion."
  type        = bool
  default     = false
}

variable "webhook_bridge_trigger_url" {
  description = "Pre-existing webhook trigger URL (skip Logic App creation if set)."
  type        = string
  default     = ""
}

# ── Agent runtime and alerting ──

variable "deploy_sre_agent" {
  description = "Deploy the SRE agent runtime and associated resources."
  type        = bool
  default     = true
}

variable "admin_principal_ids" {
  description = "Additional principal IDs granted SRE agent admin access."
  type        = list(string)
  default     = []
}

variable "reader_principal_ids" {
  description = "Additional principal IDs granted SRE Agent Reader access."
  type        = list(string)
  default     = []
}

variable "severity_threshold" {
  description = "Severity for the Application Insights smart detector alert."
  type        = string
  default     = "Sev2"

  validation {
    condition     = contains(["Sev0", "Sev1", "Sev2", "Sev3", "Sev4"], var.severity_threshold)
    error_message = "severity_threshold must be one of: Sev0, Sev1, Sev2, Sev3, Sev4."
  }
}

variable "email_receiver_address" {
  description = "Email address used for the alert action group receiver."
  type        = string
  default     = ""
}
