#!/usr/bin/env bash
set -euo pipefail

ENVIRONMENT="${1:-demo}"
SHORT_DESCRIPTION="${2:-Azure SRE Agent lab incident}"
DESCRIPTION="${3:-A test incident was generated by the Azure SRE Agent lab.}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TFVARS_FILE="$ROOT_DIR/infra/terraform/environments/${ENVIRONMENT}.tfvars"

[[ -f "$TFVARS_FILE" ]] || {
  echo "[ERROR] Environment tfvars not found: $TFVARS_FILE" >&2
  exit 1
}

tfvar() {
  local key="$1"
  awk -F= -v key="$key" '
    $1 ~ "^[[:space:]]*" key "[[:space:]]*$" {
      value = $2
      sub(/[[:space:]]*#.*/, "", value)
      gsub(/^[[:space:]"]+|[[:space:]"]+$/, "", value)
      print value
      exit
    }
  ' "$TFVARS_FILE"
}

INSTANCE="$(tfvar service_now_instance)"
USERNAME="$(tfvar service_now_username)"
PASSWORD="${TF_VAR_service_now_password:-${SERVICENOW_PASSWORD:-}}"

[[ -n "$INSTANCE" ]] || {
  echo "[ERROR] service_now_instance is missing from $TFVARS_FILE" >&2
  exit 1
}
[[ -n "$USERNAME" ]] || {
  echo "[ERROR] service_now_username is missing from $TFVARS_FILE" >&2
  exit 1
}
[[ -n "$PASSWORD" ]] || {
  echo "[ERROR] Set TF_VAR_service_now_password or SERVICENOW_PASSWORD." >&2
  exit 1
}

PAYLOAD="$(jq -n \
  --arg short_description "$SHORT_DESCRIPTION" \
  --arg description "$DESCRIPTION" \
  '{
    short_description: $short_description,
    description: $description,
    impact: "2",
    urgency: "2",
    category: "software"
  }')"

RESPONSE="$(curl --fail --silent --show-error \
  --request POST \
  --user "$USERNAME:$PASSWORD" \
  --header "Accept: application/json" \
  --header "Content-Type: application/json" \
  --data "$PAYLOAD" \
  "${INSTANCE%/}/api/now/table/incident")"

jq -r '"[OK] Created ServiceNow incident \(.result.number) (\(.result.sys_id))"' <<<"$RESPONSE"
