#!/usr/bin/env bash
set -euo pipefail

ENVIRONMENT="${1:-demo}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TFVARS_FILE="$ROOT_DIR/infra/terraform/environments/${ENVIRONMENT}.tfvars"

[[ -f "$TFVARS_FILE" ]] || {
  echo "[ERROR] Environment tfvars not found: $TFVARS_FILE" >&2
  exit 1
}

tfvar() {
  local key="$1"
  awk -F= -v key="$key" '
    $1 ~ "^[[:space:]]*" key "[[:space:]]*$" {
      value = $2
      sub(/[[:space:]]*#.*/, "", value)
      gsub(/^[[:space:]"]+|[[:space:]"]+$/, "", value)
      print value
      exit
    }
  ' "$TFVARS_FILE"
}

INSTANCE="$(tfvar service_now_instance)"
USERNAME="$(tfvar service_now_username)"
PASSWORD="${TF_VAR_service_now_password:-${SERVICENOW_PASSWORD:-${SERVICENOW_PASS:-}}}"

[[ -n "$INSTANCE" ]] || {
  echo "[ERROR] service_now_instance is missing from $TFVARS_FILE" >&2
  exit 1
}
[[ -n "$USERNAME" ]] || {
  echo "[ERROR] service_now_username is missing from $TFVARS_FILE" >&2
  exit 1
}
[[ -n "$PASSWORD" ]] || {
  echo "[ERROR] Set TF_VAR_service_now_password, SERVICENOW_PASSWORD or SERVICENOW_PASS." >&2
  exit 1
}

# The incident has to satisfy the scenario's response plan, or the agent never
# picks it up: each plan in incident-platforms/servicenow/incident-filters/
# matches on titleContains, so the title is not decoration. Impact and urgency
# drive the ServiceNow priority the plan filters on.
SCENARIO="$(tfvar scenario | tr '[:upper:]' '[:lower:]')"
case "$SCENARIO" in
  s2)
    # s2-orders-api-runtime.yaml matches titleContains "Orders API".
    DEFAULT_SHORT="Orders API returning HTTP 500 on /api/orders"
    DEFAULT_DESCRIPTION="Customers are seeing failed order submissions. The orders-api backend started returning HTTP 500 shortly after the most recent deployment."
    IMPACT="2"
    URGENCY="2"
    CATEGORY="software"
    ;;
  s3)
    # aks-incidents.yaml matches titleContains "checkout-api"; this is also the
    # display name of the Azure Monitor alert in infra/terraform/alerts.tf, so a
    # hand-created incident and an alert-driven one look the same to the agent.
    DEFAULT_SHORT="AKS checkout-api service has no endpoints"
    DEFAULT_DESCRIPTION="Checkout availability has dropped below 99% and customer checkout requests are timing out. The checkout-api pods are still Running and Ready and node CPU and memory look normal. A new checkout-api deployment rolled out shortly before the alert."
    IMPACT="1"
    URGENCY="1"
    CATEGORY="network"
    ;;
  *)
    DEFAULT_SHORT="Azure SRE Agent lab incident"
    DEFAULT_DESCRIPTION="A test incident was generated by the Azure SRE Agent lab."
    IMPACT="2"
    URGENCY="2"
    CATEGORY="software"
    ;;
esac

SHORT_DESCRIPTION="${2:-$DEFAULT_SHORT}"
DESCRIPTION="${3:-$DEFAULT_DESCRIPTION}"

echo "[INFO] Scenario ${SCENARIO:-none} (${ENVIRONMENT}): ${SHORT_DESCRIPTION}"

PAYLOAD="$(jq -n \
  --arg short_description "$SHORT_DESCRIPTION" \
  --arg description "$DESCRIPTION" \
  --arg impact "$IMPACT" \
  --arg urgency "$URGENCY" \
  --arg category "$CATEGORY" \
  '{
    short_description: $short_description,
    description: $description,
    impact: $impact,
    urgency: $urgency,
    category: $category
  }')"

RESPONSE="$(curl --fail --silent --show-error \
  --request POST \
  --user "$USERNAME:$PASSWORD" \
  --header "Accept: application/json" \
  --header "Content-Type: application/json" \
  --data "$PAYLOAD" \
  "${INSTANCE%/}/api/now/table/incident")"

jq -r '"[OK] Created ServiceNow incident \(.result.number) (\(.result.sys_id))"' <<<"$RESPONSE"
